# Generated by Django 3.2.5 on 2021-07-15 18:17

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255, unique=True)),
                ('time', models.TimeField(default=None)),
                ('date', models.DateField(default=None)),
                ('event_poster', models.ImageField(default='static/eve.jpeg', upload_to='event_poster/')),
                ('event_banner', models.ImageField(default='static/eve.jpeg', upload_to='event_banner/')),
                ('description', django_quill.fields.QuillField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_participants', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='eventrating', to='events.event')),
            ],
        ),
    ]
