# Generated by Django 3.2.5 on 2021-07-21 16:59

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_rename_member_clubprofile_members'),
        ('events', '0003_auto_20210717_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='proposal',
            field=django_quill.fields.QuillField(blank=True, default='proposal', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_event_creator', to='clubs.clubprofile'),
        ),
    ]
