# Generated by Django 3.2.5 on 2021-07-21 17:02

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210721_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='proposal',
            field=django_quill.fields.QuillField(blank=True, default=None, null=True),
        ),
    ]
