# Generated by Django 3.2.5 on 2021-07-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
