# Generated by Django 3.2.5 on 2021-07-22 06:07

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='proposal',
            field=django_quill.fields.QuillField(blank=True, default=None),
        ),
    ]
