# Generated by Django 3.2.5 on 2021-07-22 06:08

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='proposal',
            field=django_quill.fields.QuillField(blank=True, default=None, null=True),
        ),
    ]
