# Generated by Django 3.2.5 on 2021-07-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_banner',
            field=models.ImageField(default='event_banner/eve.jpeg', max_length=1024, upload_to='event_banner/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_poster',
            field=models.ImageField(default='event_poster/eve.jpeg', max_length=1024, upload_to='event_poster/'),
        ),
    ]
