# Generated by Django 3.2.5 on 2021-07-17 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('happy_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='happy_blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
