# Generated by Django 3.2.5 on 2021-07-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_blog', '0002_happy_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happy_blog',
            name='image',
            field=models.ImageField(default='media/happy_blog/images.png', upload_to='happy_blog/', verbose_name='image'),
        ),
    ]
