# Generated by Django 3.2.5 on 2021-07-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_blog', '0003_alter_happy_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happy_blog',
            name='image',
            field=models.ImageField(default='media/happy_blog/images.png', max_length=1024, upload_to='happy_blog/', verbose_name='image'),
        ),
    ]
