# Generated by Django 3.2.5 on 2021-07-24 04:48

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('happy_blog', '0006_alter_happy_blog_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happy_blog',
            name='tweet',
            field=django_quill.fields.QuillField(blank=True, verbose_name='tweet'),
        ),
    ]
