# Generated by Django 3.2.5 on 2021-07-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_clubprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='club_banner',
            field=models.ImageField(default='clubs/static/the-club-1-logo.png', upload_to='club_logo/'),
        ),
    ]
