# Generated by Django 3.2.5 on 2021-07-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_clubprofile_club_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubprofile',
            name='club_banner',
            field=models.ImageField(default='clubs/static/the-club-1-logo.png', max_length=1024, upload_to='club_logo/'),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='logo',
            field=models.ImageField(default='clubs/static/the-club-1-logo.png', max_length=1024, upload_to='club_logo/'),
        ),
    ]
